# # 原始
# optimizer: {
#   type: AdamW,
#   kwargs: {
#     lr: 0.0005,
#     weight_decay: 0.05
#   } }

# scheduler: {
#   type: CosLR,
#   kwargs: {
#     epochs: 300,
#     initial_epochs: 10
#   } }

# dataset: {
#   train: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
#            others: { subset: 'train' } },
#   val: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
#          others: { subset: 'test' } },
#   test: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
#           others: { subset: 'test' } } }
# model: {
#   NAME: PointMamba,
#   trans_dim: 384,
#   depth: 12,
#   cls_dim: 15,
#   num_heads: 6,
#   group_size: 32,
#   num_group: 128,
#   encoder_dims: 384,
#   rms_norm: False,
#   drop_path: 0.1,
#   drop_out: 0.,
# }


# npoints: 2048
# total_bs: 32
# step_per_update: 1
# max_epoch: 300
# grad_norm_clip: 10








# # # 投票 - ScanObjectNN Hardest
# optimizer: {
#   type: AdamW,
#   kwargs: {
#     lr: 0.0005,
#     weight_decay: 0.05
#   } }

# scheduler: {
#   type: CosLR,
#   kwargs: {
#     epochs: 300,
#     initial_epochs: 10
#   } }

# dataset: {
#   train: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
#            others: { subset: 'train'} },
#   val: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
#          others: { subset: 'test'} },
#   test: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
#           others: { subset: 'test'} } }

# model: {
#   NAME: PointMamba,
#   trans_dim: 384,  # 使用你指定的512维度
#   depth: 12,
#   cls_dim: 15,
  
#   # 多头投票参数 - 自动计算头数量
#   num_heads: 3,  # 这个会被自动计算覆盖
#   target_params: 22.1,  # 目标参数量(M) - 可以根据需要调整为43.6
#   voting_strategy: 'soft_vote',  # 'hard_vote', 'soft_vote', 'weighted_vote'
  
#   group_size: 32,
#   num_group: 128,
#   encoder_dims: 384,
#   rms_norm: False,
#   drop_path: 0.1,
#   drop_out: 0.,
# }

# npoints: 2048
# total_bs: 32
# step_per_update: 1
# max_epoch: 300
# grad_norm_clip: 10














# zigzag
optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.0005,
    weight_decay: 0.05
  } }

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs: 10
  } }

dataset: {
  train: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
           others: { subset: 'train'} },
  val: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
         others: { subset: 'test'} },
  test: { _base_: cfgs/dataset_configs/ScanObjectNN_hardest.yaml,
          others: { subset: 'test'} } }
model: {
  
  NAME: PointMamba,
  trans_dim: 384,
  # trans_dim: 512,
  depth: 12,
  cls_dim: 15,
  num_heads: 6,
  group_size: 32,
  num_group: 128,
  encoder_dims: 384,
  encoder_dims: 384,
  rms_norm: False,
  drop_path: 0.1,
  drop_out: 0.,
}


npoints: 2048
total_bs: 32
step_per_update: 1
max_epoch: 300
grad_norm_clip: 10





